<?php

/** @var \RvB\JsFun\ViewModel\Message $messageViewModel */
$messageViewModel = $block->getData('message_view_model');
?>

<!-- <div id="vue-test" data-mage-init='{"RvB_JsFun/js/vue-test": { "message": "Another test" }}'> -->
<div id="vue-test" data-mage-init='{"RvB_JsFun/js/vue-test": { "message": "Another test" }}'>
    <h1>{{ message }}</h1>
</div>

<script type="text/x-magento-init">
    {
        "#vue-test": {
            "RvB_JsFun/js/vue-test": { 
                "message": "<?= $messageViewModel->getMessage() ?>" 
            }
        }
    }
</script>