<!-- <div id="vue-test" data-mage-init='{"RvB_JsFun/js/vue-test": { "message": "Another test" }}'> -->
<div id="vue-test" data-mage-init='{"RvB_JsFun/js/vue-test": { "message": "Another test" }}'>
    <h1>{{ message }}</h1>
</div>

<script type="text/x-magento-init">
    {
        "#vue-test": {
            "RvB_JsFun/js/vue-test": { 
                "message": "Declarative test" 
            }
        }
    }
</script>